use faculdade
db.alunos.insertMany([
  { "ra" : 1, "nome" : "Elias", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 2, "nome" : "Owen", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 3, "nome" : "Tamisha", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 4, "nome" : "Randall", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 5, "nome" : "Sandi", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 100, "nome" : "Reyna", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 101, "nome" : "Karina", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 102, "nome" : "Lee", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 103, "nome" : "Ciara", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 104, "nome" : "Dwain", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 1000, "nome" : "Lelia", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 1001, "nome" : "Emanuel", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 1002, "nome" : "Diego", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 1003, "nome" : "Leonardo", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 1004, "nome" : "Matheus", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 100000, "nome" : "Chris", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 100001, "nome" : "Greg", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 100002, "nome" : "Julius", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 100003, "nome" : "Artur", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 1900010, "nome" : "Jonathan", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 1900011, "nome" : "Marcos", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 1900012, "nome" : "Joao", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 10001, "nome" : "Pedro", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 10002, "nome" : "Antonio", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 10003, "nome" : "Lucy", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 10004, "nome" : "Ida", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 10005, "nome" : "Mikaela", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 6, "nome" : "Tomas", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 7, "nome" : "Bruce", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 8, "nome" : "Lola", "periodo" : 6, "cod_curso" : 1 },
])