use faculdade
db.alunos.insertMany([
  { "ra" : 1, "nome" : "Elias", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 2, "nome" : "Owen", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 3, "nome" : "Tamisha", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 4, "nome" : "Randall", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 5, "nome" : "Sandi", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 6, "nome" : "Reyna", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 7, "nome" : "Karina", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 8, "nome" : "Lee", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 9, "nome" : "Ciara", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 10, "nome" : "Dwain", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 11, "nome" : "Lelia", "periodo" : 5, "cod_curso" : 1 },
  { "ra" : 12, "nome" : "Emanuel", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 13, "nome" : "Diego", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 14, "nome" : "Leonardo", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 15, "nome" : "Matheus", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 16, "nome" : "Chris", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 17, "nome" : "Greg", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 18, "nome" : "Julius", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 19, "nome" : "Artur", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 20, "nome" : "Jonathan", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 21, "nome" : "Marcos", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 22, "nome" : "Joao", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 23, "nome" : "Pedro", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 24, "nome" : "Antonio", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 25, "nome" : "Lucy", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 26, "nome" : "Ida", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 27, "nome" : "Mikaela", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 28, "nome" : "Tomas", "periodo" : 4, "cod_curso" : 1 },
  { "ra" : 29, "nome" : "Bruce", "periodo" : 6, "cod_curso" : 1 },
  { "ra" : 30, "nome" : "Lola", "periodo" : 6, "cod_curso" : 1 },
])